version: 0.2

phases:
  install:
    commands:
      - yum upgrade -y --skip-broken
      - yum install -y jq
      - yum install -y curl
      - curl -s -L https://github.com/gohugoio/hugo/releases/download/v0.123.8/hugo_0.123.8_linux-arm64.deb -o hugo.deb
      - dpkg -i hugo.deb
    finally:
      - echo Installation done
  build:
    commands:
      - echo Build started on `date`
      - echo Source files from $CODEBUILD_SRC_DIR/code
      - echo Building the project based on commit $CODE_BUILD_SOURCE_VERSION
      - cd $CODEBUILD_SRC_DIR/code
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'